[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test/unit"
evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc_version = "0.8.24"
auto_detect_remappings = false
max-line-length = 120
ffi = true

[profile.mainnet]
src = "src"
out = "out"
libs = ["lib"]
test = "test/mainnet"
eth_rpc_url = "eth_mainnet"
evm_version = "cancun"
solc_version = "0.8.24"
auto_detect_remappings = false
max-line-length = 120
ffi = true
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./" },
]


[rpc_endpoints]
eth_mainnet = "https://rpc.ankr.com/eth"
